// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Control.AsyncSeq")>]
[<assembly: AssemblyProductAttribute("src/FSharp.Control.AsyncSeq")>]
[<assembly: AssemblyDescriptionAttribute("Asynchronous sequences for F#")>]
[<assembly: AssemblyVersionAttribute("2.0.22")>]
[<assembly: AssemblyFileVersionAttribute("2.0.22")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Control.AsyncSeq"
    let [<Literal>] AssemblyProduct = "src/FSharp.Control.AsyncSeq"
    let [<Literal>] AssemblyDescription = "Asynchronous sequences for F#"
    let [<Literal>] AssemblyVersion = "2.0.22"
    let [<Literal>] AssemblyFileVersion = "2.0.22"
