name: 'Daily Perf Improver Build Steps'
description: 'Sets up the environment and builds FSharp.Control.AsyncSeq for performance testing and development'
runs:
  using: 'composite'
  steps:
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        dotnet-quality: 'ga'
    
    - name: Restore dependencies
      shell: bash
      run: dotnet restore
      
    - name: Build solution in Release mode
      shell: bash
      run: dotnet build -c Release --no-restore
      
    - name: Run tests to verify build
      shell: bash
      run: dotnet test -c Release --no-build --logger trx --results-directory TestResults/
      
    - name: Run performance baseline test
      shell: bash
      run: dotnet fsi tests/FSharp.Control.AsyncSeq.Tests/AsyncSeqPerf.fsx
      
    - name: Setup tools for performance analysis
      shell: bash
      run: |
        # Install dotnet tools for performance analysis (if needed)
        echo "Build environment ready for performance testing"
        echo "Available tools:"
        echo "- dotnet build/test for regular builds"
        echo "- dotnet fsi for F# Interactive and performance scripts"
        echo "- Release builds available in src/FSharp.Control.AsyncSeq/bin/Release/"
        echo "- Test results in TestResults/"
        
    - name: Display environment info
      shell: bash
      run: |
        echo "=== Environment Information ==="
        echo "Operating System: $(uname -a)"
        echo ".NET Version: $(dotnet --version)"
        echo "F# Compiler: $(dotnet fsc --version 2>/dev/null || echo 'F# Compiler available via dotnet')"
        echo "Working Directory: $(pwd)"
        echo "Available cores: $(nproc)"
        echo "Memory: $(free -h | head -n 2)"
        echo "=== Build Artifacts ==="
        find src/FSharp.Control.AsyncSeq/bin/Release -type f -name "*.dll" 2>/dev/null || echo "No build artifacts found"