name: Build and Test Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: '8.0.19'
    - name: Install tools
      run: dotnet tool restore
    - name: Build Test and Docs using FAKE
      run: dotnet fake build
